# Generated by Django 5.2.7 on 2025-10-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('available_coins', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
